app_auth/urls.py
from django.conf.urls import url, include
from app_auth import views

urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
]

app_wall/urls.py
from django.conf.urls import url
from app_wall import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^add_message/$', views.MessageAddView.as_view(), name='add_message'),
    url(r'^add_comment/$', views.add_comment, name='add_comment'),
    url(r'^get_content/$', views.get_content, name="get_content"),
]

webdev/urls.py
from django.conf.urls import url, include
from django.contrib import admin

SOCIAL_AUTH_URL_NAMESPACE = 'social'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('social_django.urls', namespace='social')),
    url('', include('app_auth.urls', namespace='app_auth')),
    url(r'^', include('app_wall.urls', namespace="app_wall")),
]

app_wall/models.py
from django.db import models
from django.contrib.auth.models import User

class Message(models.Model):
    user = models.ForeignKey(User)
    text = models.TextField(verbose_name='Message text', null=False)
    date_pub = models.DateTimeField(verbose_name='Date publication', auto_now_add=True, null=False)

    class Meta:
        db_table = 'messages'
        ordering = ['-date_pub']

class Comment(models.Model):
    message = models.ForeignKey(Message, null=False)
    parent = models.ForeignKey('self', null=True, blank=True)
    user = models.ForeignKey(User)
    text = models.TextField(verbose_name='Message text', null=False)
    date_pub = models.DateTimeField(verbose_name='Date publication', auto_now_add=True, null=False)

    class Meta:
        db_table = 'comments'
        ordering = ['date_pub']

app_wall/forms.py
from django import forms
from .models import Message, Comment

# form from message
class MessageForm(forms.ModelForm):
    text = forms.CharField(min_length=1, required=True, widget=forms.Textarea(attrs={
        'class': 'custom-control',
        'placeholder': 'Input your message...',
        'rows': 4,
    }), label="")

    class Meta:
        model = Message
        fields = ['text']

class CommentForm(forms.ModelForm):
    text = forms.CharField(min_length=1, required=True, widget=forms.Textarea(attrs={
        'class': 'custom-control',
        'placeholder': 'Input your comment...',
        'rows': 3,
    }), label="")

    message_id = forms.CharField(widget=forms.HiddenInput,required=True, label="")
    parent_id = forms.CharField(widget=forms.HiddenInput,required=False, label="", initial=None)

    class Meta:
        model = Comment
        exclude = ('user', 'message', 'parent',)

app_auth/views.py
from django.shortcuts import render
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.views.decorators.http import require_http_methods

# Create your views here.
@require_http_methods(["GET"])
def login(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect("/")
    else:
        return render(request, 'app_auth/login.html')

@require_http_methods(["GET"])
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect("/")

app_wall/views.py
from django.urls import reverse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.http import HttpResponse, JsonResponse
from django.views.generic import CreateView, TemplateView
from .models import Message, Comment
from .forms import MessageForm, CommentForm
from .utils import MessageList
from django.views.decorators.http import require_http_methods


class IndexView(TemplateView):
    template_name = 'app_wall/index.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data()

        messages_dict = MessageList.get_list()

        context['form_message'] = MessageForm()
        context['form_comment'] = CommentForm()
        context['messages_list'] = messages_dict

        return render(request, self.template_name, context)


class MessageAddView(CreateView):
    model = Message
    form_class = MessageForm
    http_method_names = ['post']

    def form_valid(self, form):
        form.instance.user_id = self.request.user.id
        return super(MessageAddView, self).form_valid(form)

    def form_invalid(self, form):
        return super(MessageAddView, self).form_invalid(form)

    def get_success_url(self):
        return reverse('app_wall:index')


@require_http_methods(['POST'])
def add_comment(request):
    form = CommentForm(request.POST)

    if form.is_valid():
        try:
            comment = Comment()
            comment.user = request.user
            comment.message_id = request.POST['message_id']
            comment.parent_id = request.POST['parent_id']
            comment.text = request.POST['text']
            comment.save()
        except:
            return JsonResponse({'error': 'error add comment'})

        return JsonResponse({'result': 'success'})
    else:
        return JsonResponse({'error': 'form is invalid'})

def get_content(request):
    rendered = render_to_string('app_wall/message_list.html',
                                {'messages_list': MessageList.get_list(),
                                 'request': request})
    return HttpResponse(rendered)

app_auth/templates/app_auth/login.html
{% extends 'app_wall/base.html' %}
{% block title %}
    <title>Авторизация пользователя</title>
{% endblock %}
{% block content %}
    <div class="social-group">
        <span>Войти с помощью...</span><br>
        <a class="social-btn social-fb" href="{% url "social:begin" "facebook" %}" title="Зайти через Facebook"></a>
        <a class="social-btn social-vk" href="{% url "social:begin" "vk-oauth2" %}" title="Зайти через ВКонтакте"></a>
    </div>
{% endblock %}

app_wall/templates/app_wall/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block title %}{% endblock %}
</head>
<body>
    {% block content %}{% endblock %}
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="{% static 'js/index.js' %}"></script>
</body>
</html>

app_wall/templates/app_wall/comment_list.html
{% load static %}
{% for comment in comments %}
      <li>
       <div class="comment-block">
            <div class="comment-item__info">
                <span class="comment-item__user">
                    <span class="comment-item__avatar"></span>
                    <span class="comment-item__name">{{ comment.user.first_name }} {{ comment.user.last_name }}</span>
                </span>
                <time class="comment-item__date_pub">{{ comment.date_pub|date:"d-m-Y H:i:s" }}</time>
            </div>
           <div class="comment-item__text">{{ comment.text }}</div>
            {% if request.user.is_authenticated %}
                <a href="" class="btn comment-link" data-message-id="{{ message.id }}" data-parent-id="{{ comment.id }}">Комментировать</a>
            {% endif %}
       </div>
        {% if comment.children %}
            <ul>
            {% include 'app_wall/comment_list.html' with comments=comment.children %}
            </ul>
        {% endif %}
      </li>
{% endfor %}


app_wall/templates/app_wall/index.html
{% extends 'app_wall/base.html' %}
{% block title %}
    <title>Стена сообщений</title>
{% endblock %}
{% block content %}
    <div class="container">
    {% if request.user.is_authenticated %}
    <div class="add-message clearfix">
        <div class="user">
            <strong>{{ request.user.first_name }} {{ request.user.last_name }}</strong> (<a href="/logout/">Выйти</a>)
        </div>
        <div class="user-info"></div>
        <div class="input-message">
            <form method="post" action="{% url 'app_wall:add_message' %}">
                {% csrf_token %}
                {{ form_message }}
                <button class="btn" type="submit" >Отправить</button>
            </form>
        </div>
    </div>
    {% else %}
    <div class="not-register">
        <span>Для добавления и комментирования сообщения выполните <a class="btn-login" href="/login/">вход</a></span>
    </div>
    {% endif %}

        {# hided form for reply message or content #}
    <div id="form_parking">
        <div id="form_answer" class="input-message add-message clearfix" hidden>
            <form id="form_comment_reply" action="{% url 'app_wall:add_comment' %}" method="post">
                {% csrf_token %}
                {{ form_comment }}
                <button class="btn" type="submit">Отправить</button>
            </form>
        </div>
    </div>

    {# messages #}
    <div id="content"></div>
</div>
{% endblock %}

app_wall/templates/app_wall/message_list.html
{% load static %}
<ul id="comments-list">
{% for message, comments in messages_list.items %}
    <li>
        <div class="comment-block clearfix">
            <div class="comment-item__info">
                <span class="comment-item__user">
                    <span class="comment-item__avatar"></span>
                    <span class="comment-item__name">{{ message.user.first_name }} {{ message.user.last_name }}</span>
                </span>
                <time class="comment-item__date_pub">{{ message.date_pub|date:"d-m-Y H:i:s" }}</time>
            </div>
            <div class="comment-item__text">{{ message.text }}</div>
            {% if request.user.is_authenticated %}
                <a href="" class="btn comment-link" data-message-id="{{ message.id }}">Комментировать</a>
            {% endif %}
        </div>
    {% if comments %}
        <ul>
            {% include 'app_wall/comment_list.html' %}
        </ul>
    {% endif %}
    </li>
{% endfor %}
</ul>